#!/bin/sh

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
--incognito \
'http://localhost:19200/_plugin/head' \
'http://localhost:10080/kibana/index.html#/dashboard/file/collectd.json' \
'http://localhost:10080/kibana/index.html#/dashboard/file/system.json' \
'http://localhost:10080/kibana/index.html#/dashboard/file/jmx.json' \
'http://localhost:10080/kibana/index.html#/dashboard/file/market.json' \
'http://localhost:10080/kibana/index.html#/dashboard/file/board.json' \
'http://localhost:15601/#/dashboard/Collectd?_g=()&_a=(filters:!(),panels:!((col:1,id:Collectd-CPU,row:1,size_x:6,size_y:4,type:visualization),(col:1,id:Collectd-Eth0-TX-over-the-time,row:5,size_x:6,size_y:4,type:visualization),(col:7,id:Collectd-Memory-over-the-time,row:1,size_x:6,size_y:4,type:visualization),(col:7,id:Collectd-Eth0-RX-over-the-time,row:5,size_x:6,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'\''*'\'')),title:Collectd)' \
'http://localhost:15601/#/dashboard/Collectd-JMX?_g=()&_a=(filters:!(),panels:!((col:1,id:CPU-load-over-the-time,row:1,size_x:6,size_y:3,type:visualization),(col:7,id:JMX-Loaded-Classes-over-the-time,row:4,size_x:6,size_y:3,type:visualization),(col:1,id:Threads-count-over-the-time,row:4,size_x:6,size_y:3,type:visualization),(col:7,id:JMX-Memory-Heap-over-the-time,row:1,size_x:6,size_y:3,type:visualization),(col:1,id:JMX-Memory-Pool-used,row:7,size_x:12,size_y:3,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'\''*'\'')),title:'\''Collectd%20-%20JMX'\'')' \
'http://localhost:15601/#/dashboard/Geekshop-Market-2?_g=()&_a=(filters:!(),panels:!((col:1,id:Shop-activity-over-the-time,row:1,size_x:6,size_y:3,type:visualization),(col:7,id:Sells-by-location,row:1,size_x:6,size_y:3,type:visualization),(col:1,id:Search-slash-Sell,row:4,size_x:3,size_y:3,type:visualization),(col:4,id:'\''Sells-(M-slash-F)'\'',row:4,size_x:3,size_y:3,type:visualization),(col:7,id:Sell-categories,row:4,size_x:3,size_y:3,type:visualization),(col:10,id:'\''Sells-(Name-slash-Model)-pie'\'',row:7,size_x:3,size_y:4,type:visualization),(col:7,id:Top-10-customers,row:7,size_x:3,size_y:4,type:visualization),(col:1,id:Browsers-hits,row:7,size_x:6,size_y:4,type:visualization),(col:10,id:'\''Products-(Sell)'\'',row:4,size_x:3,size_y:3,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'\''*'\'')),title:'\''Geekshop%20-%20Market'\'')' \
'http://localhost:15601/#/dashboard/Geekshop-Board?_g=()&_a=(filters:!(),panels:!((col:6,id:Average-basket,row:1,size_x:3,size_y:2,type:visualization),(col:9,id:Total-revenues,row:1,size_x:4,size_y:2,type:visualization),(col:4,id:Sells-count,row:1,size_x:2,size_y:2,type:visualization),(col:1,id:Search-slash-Sell-over-the-time,row:3,size_x:6,size_y:5,type:visualization),(col:1,id:Search-count,row:1,size_x:3,size_y:2,type:visualization),(col:7,id:Sells-by-location,row:3,size_x:6,size_y:5,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'\''*'\'')),title:'\''Geekshop%20-%20Board'\'')' \
&> /dev/null &
